// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAToxiXmOZjl-wBA7UQuRkK0nGBoo32jyc',
    appId: '1:808003925739:web:f69939d0e61ac33b6a30ae',
    messagingSenderId: '808003925739',
    projectId: 'healthy-me-4c4eb',
    authDomain: 'healthy-me-4c4eb.firebaseapp.com',
    storageBucket: 'healthy-me-4c4eb.firebasestorage.app',
    measurementId: 'G-4B2RS8BCZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx0in-fIhspKdJWZjO5exPUdp6WaEhQgU',
    appId: '1:808003925739:android:3232f8f503aedbcf6a30ae',
    messagingSenderId: '808003925739',
    projectId: 'healthy-me-4c4eb',
    storageBucket: 'healthy-me-4c4eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXE8Edys6_m9Gk6Y8xaKPU0lid99G9A5E',
    appId: '1:808003925739:ios:123ee006e3d1b2296a30ae',
    messagingSenderId: '808003925739',
    projectId: 'healthy-me-4c4eb',
    storageBucket: 'healthy-me-4c4eb.firebasestorage.app',
    iosBundleId: 'com.example.healthyMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXE8Edys6_m9Gk6Y8xaKPU0lid99G9A5E',
    appId: '1:808003925739:ios:123ee006e3d1b2296a30ae',
    messagingSenderId: '808003925739',
    projectId: 'healthy-me-4c4eb',
    storageBucket: 'healthy-me-4c4eb.firebasestorage.app',
    iosBundleId: 'com.example.healthyMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAToxiXmOZjl-wBA7UQuRkK0nGBoo32jyc',
    appId: '1:808003925739:web:911a897411e3b8a86a30ae',
    messagingSenderId: '808003925739',
    projectId: 'healthy-me-4c4eb',
    authDomain: 'healthy-me-4c4eb.firebaseapp.com',
    storageBucket: 'healthy-me-4c4eb.firebasestorage.app',
    measurementId: 'G-8VL5CCLCM2',
  );
}
